@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Joselito",
  "email": "joselito@email.com",
  "password": "chatopracacete"
}

### 

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "joselito@email.com",
  "password": "chatopracacete"
}


### 

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{

}